// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DBGet(arg1) {
  return window['go']['main']['Envious']['DBGet'](arg1);
}

export function DBSet(arg1, arg2) {
  return window['go']['main']['Envious']['DBSet'](arg1, arg2);
}

export function GetInvidiousInstance() {
  return window['go']['main']['Envious']['GetInvidiousInstance']();
}

export function GetInvidiousInstances() {
  return window['go']['main']['Envious']['GetInvidiousInstances']();
}

export function GetTrendingVideos(arg1) {
  return window['go']['main']['Envious']['GetTrendingVideos'](arg1);
}

export function GetVideo(arg1) {
  return window['go']['main']['Envious']['GetVideo'](arg1);
}

export function RestartApp() {
  return window['go']['main']['Envious']['RestartApp']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['Envious']['Search'](arg1, arg2);
}

export function SetInvidiousInstance(arg1) {
  return window['go']['main']['Envious']['SetInvidiousInstance'](arg1);
}
