// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackendConfigured() {
  return window['go']['main']['Envious']['GetBackendConfigured']();
}

export function GetInstances() {
  return window['go']['main']['Envious']['GetInstances']();
}

export function GetSelectedInstance() {
  return window['go']['main']['Envious']['GetSelectedInstance']();
}

export function GetTrendingVideos(arg1) {
  return window['go']['main']['Envious']['GetTrendingVideos'](arg1);
}

export function GetVideo(arg1) {
  return window['go']['main']['Envious']['GetVideo'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['Envious']['Search'](arg1, arg2);
}

export function SetBackendConfigured() {
  return window['go']['main']['Envious']['SetBackendConfigured']();
}

export function SetSelectedInstance(arg1) {
  return window['go']['main']['Envious']['SetSelectedInstance'](arg1);
}

export function WaitForBackend() {
  return window['go']['main']['Envious']['WaitForBackend']();
}
