// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInvidiousApiInstances() {
  return window['go']['main']['InvidiousDesktop']['GetInvidiousApiInstances']();
}

export function GetPopular() {
  return window['go']['main']['InvidiousDesktop']['GetPopular']();
}

export function GetSelectedInvidiousInstance() {
  return window['go']['main']['InvidiousDesktop']['GetSelectedInvidiousInstance']();
}

export function SetSelectedInvidiousInstance(arg1) {
  return window['go']['main']['InvidiousDesktop']['SetSelectedInvidiousInstance'](arg1);
}
