// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetApiInstances():Promise<Array<string>>;

export function GetPopular():Promise<Array<main.Video>>;

export function GetSelectedInstance():Promise<string>;

export function GetTrending():Promise<Array<main.Video>>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function SetSelectedInstance(arg1:string):Promise<boolean>;
