// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApiInstances() {
  return window['go']['main']['InvidiousDesktop']['GetApiInstances']();
}

export function GetPopular() {
  return window['go']['main']['InvidiousDesktop']['GetPopular']();
}

export function GetSelectedInstance() {
  return window['go']['main']['InvidiousDesktop']['GetSelectedInstance']();
}

export function GetTrending() {
  return window['go']['main']['InvidiousDesktop']['GetTrending']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['InvidiousDesktop']['Login'](arg1, arg2);
}

export function SetSelectedInstance(arg1) {
  return window['go']['main']['InvidiousDesktop']['SetSelectedInstance'](arg1);
}
