// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInvidiousApiInstances():Promise<Array<string>>;

export function GetSelectedInvidiousInstance():Promise<string>;

export function SetSelectedInvidiousInstance(arg1:string):Promise<boolean>;
