// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shared} from '../models';

export function GetConfigured():Promise<boolean>;

export function GetInstanceApi():Promise<string>;

export function GetInstanceFrontend():Promise<string>;

export function GetInstancesApi(arg1:string):Promise<Array<{[key: string]: string}>>;

export function GetProvider():Promise<string>;

export function GetTrending():Promise<Array<shared.Video>>;

export function GetVideo(arg1:string):Promise<shared.Video>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetInstance(arg1:string):Promise<void>;

export function SetProvider(arg1:string):Promise<void>;
