// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shared} from '../models';

export function DBGet(arg1:string,arg2:string):Promise<any>;

export function DBGetWithDefault(arg1:string,arg2:string,arg3:any):Promise<any>;

export function DBSet(arg1:string,arg2:any):Promise<void>;

export function GetInstancesApi(arg1:string):Promise<Array<{[key: string]: string}>>;

export function GetTrending():Promise<Array<shared.Video>>;

export function GetVideo(arg1:string):Promise<shared.Video>;
