// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {invidious} from '../models';

export function GetBackendConfigured():Promise<boolean>;

export function GetInstances():Promise<Array<invidious.Instance>>;

export function GetPopularVideos():Promise<Array<invidious.Video>>;

export function GetSelectedInstance():Promise<invidious.Instance>;

export function GetTrendingVideos():Promise<Array<invidious.Video>>;

export function GetVideo(arg1:string):Promise<invidious.Video>;

export function Search(arg1:string,arg2:invidious.SearchOptions):Promise<Array<invidious.SearchItem>>;

export function SetBackendConfigured():Promise<void>;

export function SetSelectedInstance(arg1:invidious.Instance):Promise<void>;
