// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DBGet(arg1, arg2) {
  return window['go']['main']['Tubed']['DBGet'](arg1, arg2);
}

export function DBGetWithDefault(arg1, arg2, arg3) {
  return window['go']['main']['Tubed']['DBGetWithDefault'](arg1, arg2, arg3);
}

export function DBSet(arg1, arg2) {
  return window['go']['main']['Tubed']['DBSet'](arg1, arg2);
}

export function GetInstancesApi(arg1) {
  return window['go']['main']['Tubed']['GetInstancesApi'](arg1);
}

export function GetTrending() {
  return window['go']['main']['Tubed']['GetTrending']();
}

export function GetVideo(arg1) {
  return window['go']['main']['Tubed']['GetVideo'](arg1);
}
