// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackendConfigured() {
  return window['go']['main']['Tubed']['GetBackendConfigured']();
}

export function GetInstances() {
  return window['go']['main']['Tubed']['GetInstances']();
}

export function GetPopularVideos() {
  return window['go']['main']['Tubed']['GetPopularVideos']();
}

export function GetSelectedInstance() {
  return window['go']['main']['Tubed']['GetSelectedInstance']();
}

export function GetTrendingVideos() {
  return window['go']['main']['Tubed']['GetTrendingVideos']();
}

export function GetVideo(arg1) {
  return window['go']['main']['Tubed']['GetVideo'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['Tubed']['Search'](arg1, arg2);
}

export function SetBackendConfigured() {
  return window['go']['main']['Tubed']['SetBackendConfigured']();
}

export function SetSelectedInstance(arg1) {
  return window['go']['main']['Tubed']['SetSelectedInstance'](arg1);
}
