// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigured() {
  return window['go']['main']['Tubed']['GetConfigured']();
}

export function GetInstanceApi() {
  return window['go']['main']['Tubed']['GetInstanceApi']();
}

export function GetInstanceFrontend() {
  return window['go']['main']['Tubed']['GetInstanceFrontend']();
}

export function GetInstancesApi(arg1) {
  return window['go']['main']['Tubed']['GetInstancesApi'](arg1);
}

export function GetProvider() {
  return window['go']['main']['Tubed']['GetProvider']();
}

export function GetTrending() {
  return window['go']['main']['Tubed']['GetTrending']();
}

export function GetVideo(arg1) {
  return window['go']['main']['Tubed']['GetVideo'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['Tubed']['SetConfig'](arg1, arg2);
}

export function SetInstance(arg1) {
  return window['go']['main']['Tubed']['SetInstance'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['Tubed']['SetProvider'](arg1);
}
