name: Wails build

on: [push, pull_request]
      
permissions:
    contents: write
    packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - platform: linux/amd64 
            os: ubuntu-latest
          - platform: windows/amd64 
            os: windows-latest
          - platform: darwin/universal 
            os: macos-latest
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: deesturbe/wails-build-action@v1.0.1
        with:
          build-name: Invidious Desktop
          build-platform: ${{ matrix.build.platform }}
          package: true