name: Wails build

on:
  release:
    types: [published]
      
permissions:
    contents: write
    packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: "Invidious Desktop", platform: linux/amd64, os: ubuntu-latest},
          {name: "Invidious Desktop", platform: windows/amd64, os: windows-latest},
          {name: "Invidious Desktop", platform: darwin/amd64, os: macos-latest},
          {name: "Invidious Desktop", platform: darwin/arm64, os: macos-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
